services:
  postgres:
    image: postgres
    container_name: telegram-bot-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack-server
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
    name: telegram-bot-pgdata